- name: Ensure group "marmich" exists
  tags: groups,marmich,users
  ansible.builtin.group:
    name: marmich
    state: present

- name: Create user for marmich
  tags: marmich,sudo,users
  ansible.builtin.user:
    name: marmich
    group: marmich
    groups: adm,ansible,{{ sudo_group }}
    state: present
    comment: "Marios Michalopoulos"
    password: "{{ marmich_passwd }}"
    shell: /bin/bash

- name: Add sudoers file for marmich
  tags: marmich,settings,sudo,system,users
  ansible.builtin.copy:
    src: users/sudoers_marmich
    dest: /etc/sudoers.d/marmich
    owner: root
    group: root
    mode: 0440

- name: Create .ssh directory for marmich
  tags: dotfiles,marmich,ssh,users
  ansible.builtin.file:
    path: "{{ item.dir }}"
    state: directory
    owner: marmich
    group: marmich
    mode: 0700
  with_items:
    - { dir: "/home/marmich/.ssh" }

- name: Add public key for marmich
  tags: dotfiles,marmich,ssh,ssh-keys,users
  ansible.posix.authorized_key:
    user: marmich
    key: "{{ item }}"
  with_file:
    # TODO: Add public key
    - users/marmich/ssh/marmich_id_ed25519.pub

- name: Create config directories for marmich
  tags: dotfiles,marmich,users,zsh
  ansible.builtin.file:
    path: /home/jay/{{ item.dir }}
    state: directory
    owner: jay
    group: jay
    mode: 0700
  with_items:
    - { dir: ".bash" }
    - { dir: ".config" }
    - { dir: ".config/htop" }
    - { dir: ".zsh" }

- name: Copy dotfiles for marmich
  tags: dotfiles,users,marmich,users,zsh
  ansible.builtin.copy:
    src: users/marmich/{{ item.src }}
    dest: /home/marmich/{{ item.dest }}
    owner: marmich
    group: marmich
    mode: 0600
  with_items:
    - { src: "bash/bash_aliases", dest: ".bash/bash_aliases" }
    - { src: "bash/bash_profile", dest: ".bash_profile" }
    - { src: "bash/bash_prompt", dest: ".bash/bash_prompt" }
    - { src: "bash/bash_functions", dest: ".bash/bash_functions" }
    - { src: "bash/bashrc", dest: ".bashrc" }
    - { src: "bash/profile", dest: ".profile" }
    - { src: "git/gitconfig", dest: ".gitconfig" }
    - { src: "htop/htoprc", dest: ".config/htop/htoprc" }
    - { src: "inputrc", dest: ".inputrc" }
    - { src: "zsh/zshrc", dest: ".zshrc" }

- name: Copy individual zsh config files for marmich
  tags: dotfiles,marmich,users,zsh
  ansible.builtin.copy:
    src: users/marmich/zsh/{{ item.src }}
    dest: /home/marmich/.zsh/{{ item.src }}
    owner: marmich
    group: marmich
    mode: 0600
  with_items:
    - { src: "aliases.zsh" }
    - { src: "bindkey.zsh" }
    - { src: "completion.zsh" }
    - { src: "exports.zsh" }
    - { src: "functions.zsh" }
    - { src: "history.zsh" }
    - { src: "path.zsh" }
    - { src: "plugins.zsh" }
    - { src: "prompt.zsh" }
    - { src: "setopt.zsh" }
    - { src: "theming.zsh" }

