- name: Install utility packages
  tags: packages,system,settings
  ansible.builtin.package:
    state: latest
    name:
      - at
      - colordiff
      - curl
      - "{{ dns_utils_package}}"
      - htop
      - iotop
      - "{{ lm_sensors_package }}"
      - lsof
      - ncdu
      - neofetch
      - net-tools
      - "{{ nfs_client_package }}"
      - "{{ rename_package }}"
      - rsync
      - traceroute
      - "{{ vim_package }}"
      - wget
      - whois
      - zsh
